### ISSUE TITLE
Quote Issue

### ISSUE THREAD

**Issue by theapache64** [mhashim6/System-Command-Executor#2]
I am facing an error while executing commands with single quotes or double quotes. Below given reproducible  code input.

```
public static void main(String[] args) {

        Command cmd = new CommandBuilder("ping").withArgs("'google.com'").build();
        ExecutionOutputPrinter eop = new ExecutionOutputPrinter(new Appender() {

            @Override
            public void appendStdText(String text) {
                System.out.println(text);
                //or your code to show std output lines.
            }

            @Override
            public void appendErrText(String text) {
                System.err.println(text);
                //or your code to show error lines.
            }
        });

        try {
            ProcessMonitor pMonitor = CommandExecutor.execute(cmd, null, eop); //execute the command, redirect the output to eop.
            ExecutionReport report = pMonitor.getExecutionReport(); //blocks until the process finishes or gets aborted.

            String commandLine = cmd.string();
            int exitCode = report.exitValue();

            System.out.printf("command line: %s\nexecution finished with exit code: %d\n\n", commandLine, exitCode);
        } catch (UnrecognisedCmdException e) {
            System.err.println(e);
        }
    }
```

**Comment by mhashim6** [comment]
The way that quotes are treated currently is by respecting their existence, meaning they are sure to be passed to the command executor (e.g, shell). the shell may _lift_ the quotes from `google.com` automatically, but we can't do the same in the library because then we're assuming the quotes are not to be enforced, in other words–useless.
In your use case, you can try and omit unnecessary quotes, and the current implementation should (hopefully) work. according to [this](https://stackoverflow.com/questions/12124935/processbuilder-adds-extra-quotes-to-command-line).

Could you try that? Also, is it possible to share the command you're trying to execute?

Thanks.

**Comment by theapache64** [comment]
> In your use case, you can try and omit unnecessary quotes, and the current implementation should (hopefully) work. according to this.

For some command, the quote can't be removed. For eg: [ffmpeg's complex filters](https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video). 


The issue will also occur when we pass params with spaces. for eg:

`Command cmd = new CommandBuilder("ls").withArgs("Fold Name Without Name").build();`

In the above scenario, the current implementation treats each word as each parameter.

**Comment by mhashim6** [comment]
> > In your use case, you can try and omit unnecessary quotes, and the current implementation should (hopefully) work. according to this.
> 
> For some command, the quote can't be removed. For eg: [ffmpeg's complex filters](https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video).

Can you try these two examples?
```java
Command cmd = new CommandBuilder("ffmpeg -i input.mkv -filter:v \"setpts=0.5*PTS\" output.mkv").build();
```

```java
Command cmd = new CommandBuilder("ffmpeg -i input.mkv -filter:v setpts=0.5*PTS output.mkv").build();
```

**Comment by theapache64** [comment]
It's getting failed. The command runs, but the program can't handle it. I've mailed you a screen record.

**Comment by mhashim6** [comment]
> It's getting failed. The command runs, but the program can't handle it. I've mailed you a screen record.

Thanks for the detailed info. for the time being, this should work (tested on my machine):
```java
Command cmd = new CommandBuilder("ffmpeg -i input.mkv -filter:v setpts=0.5*PTS output.mkv").build();
```

I'll make a fix when I have the time.

**Comment by mhashim6** [comment]
check #3 .

**Comment by theapache64** [comment]
I've checked the PR. Now it's working properly. :confetti_ball: :smile: Can I get an updated release ?
